### ISSUE TITLE
Add zoom in/out button

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/gridviz#104]
It would be nice to have a way to include easily some zoom in/out buttons. With "+" and "-" text.
Just like we have in https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/grids

Maybe something similar to what exists in openlayer and leaflet, see:
https://openlayers.org/en/latest/apidoc/module-ol_control_Zoom-Zoom.html
https://leafletjs.com/reference.html#control-zoom
https://www.tutorialspoint.com/leafletjs/leafletjs_controls.htm

**Comment by joewdavies** [comment]
`app.addZoomButtons()` and `app.addFullscreenButton()` are now available: https://eurostat.github.io/gridviz/docs/reference#app-configuration.

Both classes ([ZoomButtons ](https://github.com/eurostat/gridviz/blob/master/src/button/ZoomButtons.js)and [FullscreenButton](https://github.com/eurostat/gridviz/blob/master/src/button/FullscreenButton.js)) inherit from the [Button](https://github.com/eurostat/gridviz/blob/master/src/button/Button.js) parent class.
