### ISSUE TITLE
Blend Modes not working in Firefox

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#107]
Open
https://eurostat.github.io/gridviz/examples/blending_alpha.html
in Firefox (tested with 117.0.1 on macOS 13.5.2 and 102.14esr on Windows 10)

looks like expected at first:

![ff1](https://github.com/eurostat/gridviz/assets/4449821/95bafb82-78cb-4e7c-82ab-777661fb7913)

but turns into a black page the once you mouse over the map:

![ff2](https://github.com/eurostat/gridviz/assets/4449821/b1432cad-770d-4c7d-a607-61ff4119193e)

**Comment by jgaffuri** [comment]
Thank you ! I observe the same. The screen gets darker and darker. It works fine on chrome and also edge. There might be a differnent implementation of these blend modes in firefox. I'll check this and find a workaround !

**Comment by jgaffuri** [comment]
Making a test of this page
https://www.w3schools.com/jsref/tryit.asp?filename=tryhtml5_canvas_globalcompop
on chrome/IE and firefox does not show the same result. Firefox seems not to implement globalCompositeOperation property the same way as chrome and IE.
A workaround could be to detect when the navigator is firefox and in this case, not use "multiply" but force to "normal". This will degrade the experience of firefox users (4.6% of the users in sept 2023 according to https://www.w3schools.com/browsers/) but that's the best we could do.

**Comment by jgaffuri** [comment]
To detect the the navigator is or is not Firefox, here is the code:

```
if (navigator.userAgent.indexOf("Firefox") != -1) {
    // This browser is Firefox
    console.log("This is Firefox!");
} else {
    // This is not Firefox
    console.log("This is not Firefox.");
}
```

I have used it in Germany demo page https://eurostat.github.io/gridviz/examples/DE.html to adapt the blend mode in the case of Firefox, and use "normal" instead of "multiply":

```
//use this to fix blend mode bug in firefox
const blendMultiplyOverrideFirefox = navigator.userAgent.indexOf("Firefox") != -1 ? "normal" : "multiply";
...
blendOperation: (zf) => zf < 6 ? blendMultiplyOverrideFirefox : "normal"
```

**Comment by jgaffuri** [comment]
This is fixed. See #110 .
