### ISSUE TITLE
BlendModes fixed in Firefox

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#110]
as per
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

the *default* value for `CanvasRenderingContext2D.globalCompositeOperation`

is `source-over`

therefore, if we change the following in GridViz (/src/App.js)

`//restore default alpha and blend operation`  
`  this.cg.ctx.globalAlpha = 1.0`  
`  this.cg.ctx.globalCompositeOperation = "normal"`  

to  

`  this.cg.ctx.globalCompositeOperation = "source-over"`  

BlendModes work identical in Firefox as in Safari, see here in action
https://wahlatlas.net/experimente/z11exposee/gridviz/blendMode_Test.html#!4194642,2998537,0.27

**Comment by jgaffuri** [comment]
Excellent ! That was the issue.
The default value for firefox and also chrome is "source-over" and not "normal". I have implemented it and it fixes all. Multiply now works in firefox. No need for workaround !

**Comment by jgaffuri** [comment]
This is implemented in the new version 2.1.1.
I corrected /GridViz/examples/DE.html
