### ISSUE TITLE
Add BlendMode to Documentation

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#111]
Should #110 turn out to achieve cross-browser and cross-os compatibility for blendmodes, please add the 

`blendOperation: (zf) => zf<1 ? "multiply" : "none",`

syntax to the documentation

**Comment by jgaffuri** [comment]
See: https://eurostat.github.io/gridviz/docs/reference#multi-layer-multi-style-and-multi-scale-mapping
