### ISSUE TITLE
Add line layer unclear

### ISSUE THREAD

**Issue by joewdavies** [eurostat/gridviz#119]
There is currently no clear way to add a line layer.

I am trying to add an extra 'boundaries' layer on top of NUTS2JSON and struggling with it.

For example, users might want to add line layers that might not necessarily be boundaries: https://eurostat.github.io/gridviz/docs/reference#showing-boundaries

**Comment by jgaffuri** [comment]
OK, I will have a look !

**Comment by jgaffuri** [comment]
Note that in version 3, boundaryLayer was renamed "GeoJSONLayer". It will be extended so that it handles any geojson data, not only line / boundaries as currently.
Coming... soon !

**Comment by joewdavies** [comment]
Fixed with https://github.com/eurostat/gridviz/commit/860acad01060081f7f3acc13d5fa37525a8c9f8e
