### ISSUE TITLE
Legend div definition

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/gridviz#123]
Currently, the div id is given to legendDivId option:
const map = new gridviz.Map(document.getElementById('map'), { x: 4500000, y: 2900000, z: 1000, legendDivId: 'ext_legend' })
instead, it should be a container. So that we can do instead something like:
const map = new gridviz.Map(document.getElementById('map'), { x: 4500000, y: 2900000, z: 1000, legendDiv: document.getElementById('ext_legend') })

**Comment by joewdavies** [comment]
Fixed with https://github.com/eurostat/gridviz/commit/9b5f065f72bb66e8b660f65935af44949c900df9
