### ISSUE TITLE
Migration Guide v2 => v3

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#127]
I have to admit that I couldn't follow this project in the last 12 months and am still with GridViz Version 2.
Is there a migration guide or some doc that explains the thinking behind v3, the changes and how to migrate, especially

* can the tiled csv data from v2 be used with v3 
* what are the main goals of v3 
* when is it worth upgrading 
* what are the expected changes

**Comment by jgaffuri** [comment]
Here it is:
https://github.com/eurostat/gridviz/blob/master/docs/changelog.md

I will link it to the release !

**Comment by jgaffuri** [comment]
Here is the release: https://github.com/eurostat/gridviz/releases/tag/3.0.0
