### ISSUE TITLE
Blending multiple background layers

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#128]
There are separate WMS services for topographic background map as well as hillshading in Germany (see [basemap.de](https://basemap.de/en/))

So far I can display one *or* the other based on zoom level. Am I missing something here or is blending two backgrounds prohibitive in terms of cpu cycles? Ideally I'd like to blend using blend-modes, as is possible for the data layers.

Example images 

![topo](https://github.com/user-attachments/assets/fd9de84a-f626-4e6e-a48d-5f952bdd125c)
![hillshade](https://github.com/user-attachments/assets/ff3686cf-09ab-4482-9ee7-52f2e8d18c33)

**Comment by wahlatlas** [comment]
As per the v3 changelog
_Layers grouping: No more distinction beteen grid layers, background layers and other layers. One stack of layers par map, whatever the type, order and number._

this should be possible then, will try it out (later) and report back

**Comment by jgaffuri** [comment]
Yes: It is now possible to define several background layers, and show them in whatever order. I never tried what you describe but I am rather confident it should work !

**Comment by wahlatlas** [comment]
Thanks and sorry for the looong wait, but it works perfectly, see
https://wahlatlas.net/experimente/testcases/gridviz3_issue_153_mapLayersVisible.html

I've opened #153 to ask for the intended way of toggling layer visibility
