### ISSUE TITLE
Parquet files NULL values are parsed as 0

### ISSUE THREAD

**Issue by joewdavies** [eurostat/gridviz#134]
NULL should not be parsed as 0

e.g. **educ_2023_n1** here will arrive to the preprocessor function as **0**, when in it is in fact NULL:

Parquet:
```
x,y,cntr_id,tot_p_2021,health_2020_n1,health_2020_n3,health_2023_n1,health_2023_n3,educ_2020_n1,educ_2023_n1,educ_2023_n3,nb,cntr_id2,xt,yt
0,39,ES,5,9.54,12.09,8.81,11.62,2.0,,,1,ES,29,16
```
DevTools preprocessor raw cell:
![image](https://github.com/user-attachments/assets/89936951-b186-4e79-a81e-5fed7d195c42)

**Comment by jgaffuri** [comment]
It should be solved in gridviz-parquet version 1.1.0.
