### ISSUE TITLE
Color Legend not working with simple color function

### ISSUE THREAD

**Issue by joewdavies** [eurostat/gridviz#137]
Trying to make a simple legend using the same colour function as the style doesnt work:

```    
    //define color for each cell c
    const colorFunction = (cell, resolution) => {
        const density = (1000000 * cell.TOT_P_2021) / (resolution * resolution)
        if (density > 1500) return '#993404'
        else if (density > 600) return '#d95f0e'
        else if (density > 200) return '#fe9929'
        else if (density > 60) return '#fec44f'
        else if (density > 15) return '#fee391'
        else return '#ffffd4'
    }

   //define style
    const style = new ShapeColorSizeStyle({ color: colorFunction })

    //add legend
    const legend = new ColorLegend({
        title: 'Population',
        colorScale: colorFunction,
        ticks: 5,
        textScale: (t) => t * 20000,
    })
```

How can a user make a color legend from their colorFunction?

**Comment by jgaffuri** [comment]
In ColorLegend definition, 'colorScale' property is a function [0,1] -> color. It should not be the same function used in the style definition.
ColorLegend is designed by default for continuous legends. For discrete legends, ColorDiscreteLegend should be used instead: https://eurostat.github.io/gridviz/docs/reference#color-discrete-legend
