### ISSUE TITLE
Key and Tooltip mismatch in examples/EUR.html ?

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#82]
<img width="380" alt="Bildschirmfoto 2023-01-03 um 16 28 18" src="https://user-images.githubusercontent.com/4449821/210389139-1e7f3f3d-8349-4245-af77-de164eb865c0.png">

This is 1km grid I assume and therefore the tooltip value looks more plausible to me than the color key  

<img width="569" alt="Bildschirmfoto 2023-01-03 um 16 38 04" src="https://user-images.githubusercontent.com/4449821/210390566-be46b5eb-3cfd-413c-a1de-1c2ae7ff1f73.png">  

Source [atlas.zensus2011.de](https://atlas.zensus2011.de/)

**Comment by jgaffuri** [comment]
This was indeed a bug in the legend settings: It is corrected now.
See: https://eurostat.github.io/gridviz/examples/EUR.html
Thank you very much for pointing this out !
