### ISSUE TITLE
opts.onZoomStartFun doesn't seem to fire

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#88]
from the three zoom/pan events in the options object

    onZoomStartFun: (event) => {
        console.log('pan/zoom start', event)
    },
    onZoomFun: (event) => {
        console.log('zoom', event)
    },
    onZoomEndFun: (event) => {
        console.log('pan/zoom end', event)
    },

it looks to me as if the `onZoomStartFun` event doesn't fire  
I do see "zoom" and "pan/zoom end" in the console but never "pan/zoom start"

**Comment by joewdavies** [comment]
Thanks for letting us know!

You're right, the function was being overwritten so the user-specific function was not being executed!

This should now be fixed in 2.0.34 https://github.com/eurostat/gridviz/releases/tag/2.0.34
