### ISSUE TITLE
Data pre-processing and cellInfoHTML not possible in same layer

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#92]
I tried everything, obeyed every comma and bracket, different ordering, but it seems that data pre-processing and cellInfoHTML are not possible in the same layer. Once you use `preprocess` everything in `cellInfoHTML` will be ignored and you just get the default tooltip with column name and value.  

Among your examples I couldn't find an example that uses both.

**Comment by jgaffuri** [comment]
I added this new test:
https://eurostat.github.io/gridviz/examples/test/preprocess_and_tooltip.html
which uses both  `preprocess` and `cellInfoHTML` together and it seems to work well.
Could you share the exact code where the problem occurs? There might be something else which causes this interference.

**Comment by wahlatlas** [comment]
Sorry, my fault, I had the nesting wrong, didn't realize that pre-processing and cellInfoHTML are within the same curly brackets.  
Thanks for your added example, that's how I understand things best.
