### ISSUE TITLE
WMS background would like to have filterColor as well

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#93]
https://github.com/eurostat/gridviz/blob/master/docs/reference.md#background-layer

looks like the wms background layer does not offer filterColor

also, it is probably

`filterColor: (zf) => "#ffffff66",`

instead of 

`filterColor: zf => "#ffffff66",`

![missing_bracket](https://github.com/eurostat/gridviz/assets/4449821/bb09730f-06f8-40a1-914b-2a395ff4ceaf)

**Comment by jgaffuri** [comment]
filterColor is added to WMS from version 2.0.26

**Comment by wahlatlas** [comment]
This works beautifully, thank you!
