### ISSUE TITLE
Combine ShapeColorSizeStyle with TextStyle

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#94]
I could see some real world use cases, here's a photohopped version of how I imagine this.  
Probably the additional text-layer would only make sense on lower zoom factors.  

![combined](https://github.com/eurostat/gridviz/assets/4449821/171c17fd-c654-4e62-86ec-02b6192eedb6)

**Comment by jgaffuri** [comment]
Very nice example indeed !
You may also show the labels only for big enough circles. And adapt the font size to the circle size so that the text remain inside the circle.

**Comment by wahlatlas** [comment]
Has this been added to a fork? I can't see where/how this would work or has it been postponed?

**Comment by jgaffuri** [comment]
Sorry. I misunderstood your message ! I thought your image was something you already did with gridviz.
In fact, it can be done by defining 2 styles for your layer. One with sized circles and another one on top with TextStyle. A layer has an array of styles which already allows such combinaison. Such combinaison is used for the styles lego and Tanaka for example.
I will provide a new axample showing that.

**Comment by wahlatlas** [comment]
Ah, now I get it, thanks!

"A layer has an array of styles" is the key, I had the nesting wrong again, this time the square brackets.

**Comment by jgaffuri** [comment]
Yes, all these brackets with arrays of brackets... it can become confusing !
