### ISSUE TITLE
csv-tiling with Python, example implementation

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#95]
I implemented csv-tiling in Python/Pandas and it seems to work reliable, so wanted to share a Jupyter Notebook and am glad to listen to suggestions

https://github.com/wahlatlas/grid_data/blob/main/gridviz_tiled_csv.ipynb

**Comment by jgaffuri** [comment]
I have bookmarked this in a dedicated folder in the gridtiler repository: https://github.com/eurostat/gridtiler/tree/main/py
This may be a good basis for a future python-based gridtiler.
