### ISSUE TITLE
Aria labels on tooltip

### ISSUE THREAD

**Issue by wahlatlas** [eurostat/gridviz#97]
I have to admit, I am new to aria labels but it looked to me as if the tooltip would not be read by VoiceOver (screenreader assistive technology built into MacOS) until I injected the following aria labels

`d3.select("#tooltip_eurostat").attr("role","tooltip").attr("aria-live","polite")`

**Comment by joewdavies** [comment]
First time i've heard of this to be honest! I'll add those attributes to the tooltip.

**Comment by joewdavies** [comment]
Added in [2.0.35](https://github.com/eurostat/gridviz/releases/tag/2.0.35)
